### ISSUE TITLE
Error with integration

### ISSUE THREAD

**Issue by fslef** [pcourbin/imaprotect#173]
Hello Pierre,

The Ima Protect integration seems to not work anymore since a couple of days ago.
I tried to reconfigure the integration from scratch but it was unsucessfull.

I would be glad to support you for the troubleshooting but I'm not sure how to proceed.

Thanks a lot in advance 
François.

## Debug log
```
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.imaprotect
Source: custom_components/imaprotect/coordinator.py:63
Integration: IMA Protect Alarm (documentation, issues)
First occurred: 13 février 2023 à 09:05:54 (1045 occurrences)
Last logged: 08:26:08

Unexpected error fetching imaprotect data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/imaprotect/coordinator.py", line 63, in _async_update_data
    cameralist = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyimaprotect/__init__.py", line 105, in get_images_list
    capture_list = self._capture_list()
  File "/usr/local/lib/python3.10/site-packages/pyimaprotect/__init__.py", line 140, in _capture_list
    response_json = json.loads(response.content)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

And also this error: 
```
Logger: pyimaprotect
Source: /usr/local/lib/python3.10/site-packages/pyimaprotect/__init__.py:158
First occurred: 13 février 2023 à 09:05:54 (3136 occurrences)
Last logged: 08:26:07


Can't get the token to login, step 'Login/TokenLogin'. Please, contact the developer.
```

## Version of the custom_component
v1.0.2

**Comment by pcourbin** [comment]
Bonjour François, 
Grâce à @Thesola10, tout semble de nouveau fonctionnel (v1.0.3), avec en plus une fonctionnalité pour récupérer les images des caméras. Merci encore à lui !

**Comment by fslef** [comment]
Cool. Je confirme que ca fonctionne à nouveau.
Merci @Thesola10
