### ISSUE TITLE
Pb suite MAJ 2023.5 de HomeAssistant

### ISSUE THREAD

**Issue by ChtiKev** [pcourbin/imaprotect#202]
Bonjour

Déjà merci pour l'intégration d'IMAProtect. C'est hyper pratique.

L'intégration IMAProtect est en échec avec le message d'erreur "Échec de la configuration" dans la page des intégrations.
A priori, suite à la MAJ 2023.5, la fonction async_setup_platforms qui était deprecated a été supprimée (cf. [https://www.home-assistant.io/changelogs/core-2023.5/](https://www.home-assistant.io/changelogs/core-2023.5/).

Version intégration ImaProtect : v1.0.3
Configuration : RPI 4 + SSD

Voici le log de l'erreur rencontrée : 

Logger: homeassistant.config_entries
Source: custom_components/imaprotect/__init__.py:44
Integration: IMA Protect Alarm (documentation, issues)
First occurred: 4 mai 2023 à 15:56:24 (2 occurrences)
Last logged: 4 mai 2023 à 16:59:34

Error setting up entry Alarme for imaprotect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/imaprotect/__init__.py", line 44, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

Merci.

**Comment by bcze91** [comment]
Bonjour,

Pour contourner, j'ai appliqué la modification proposée sur un autre composant HACS : https://github.com/home-assistant/core/issues/92562.

Il s'agit d'éditer le fichier /config/custom_components/imaprotect/__init__.py

et de remplacer la ligne 44 (sous le commentaire) qui contient la fonction deprecated "hass.config_entries.async_setup_platforms" par les 2 lignes suivantes

    # Set up all platforms for this device/entry.
    for platform in PLATFORMS:
        hass.async_create_task(hass.config_entries.async_forward_entry_setup(entry, platform))

en respectant l'indentation ... puis rédemarrer HA

Et encore merci au créateur du composant

Bruno

**Comment by fslef** [comment]
Genial, merci pour la solution @bcze91.
@pcourbin, j'ai poussé une pr pour la correction #205

**Comment by pcourbin** [comment]
Bonjour à tous, 

Merci infiniment pour vos retours @ChtiKev, corrections @bcze91 et PR @fslef !
Je viens de faire la nouvelle release.

Pour information, je n'ai plus cette alarme chez moi... si quelqu'un veut être ajouté en contributeur pour continuer à maintenir ces intégration/package plus facilement, n'hésitez pas à me le dire surtout 😉
