### ISSUE TITLE
Impossible de piloter l'alarme

### ISSUE THREAD

**Issue by werkey** [pcourbin/imaprotect#208]
#Description
Bonjour, 
Merci pour votre travail sur l'intégration
Depuis hier midi l'intégration ne fonctionne plus. Le matin aucun problème pour activer l'alarme, en revanche le soir plus possible de la piloter.
IMA protect à plusieurs problèmes de serveur en ce moment (notamment au niveau de la connexion sur appli semaine dernière).
J'ai tenté de supprimer et de reconfigurer l'intégration sans succès.
ps : je suis sûr de mon couple identifiant/mdp

#Configuration:
Core 2024.3.3
Supervisor 2024.03.1
Operating System 12.1
Interface utilisateur 20240307.0
Intégration : v1.0.4

#Logs
Dans les logs :
Enregistreur: pyimaprotect
Source: /usr/local/lib/python3.12/site-packages/pyimaprotect/__init__.py:191
S'est produit pour la première fois: 28 mars 2024 à 21:11:49 (50 occurrences)
Dernier enregistrement: 13:07:43

Can't get the token to read the status, step 'Login/TokenStatus'. Please, check your logins. You must be able to login on https://www.imaprotect.com.

Enregistreur: pyimaprotect
Source: /usr/local/lib/python3.12/site-packages/pyimaprotect/__init__.py:91
S'est produit pour la première fois: 28 mars 2024 à 21:20:09 (11 occurrences)
Dernier enregistrement: 11:29:42

Can't change the status, step 'SetStatus'. Please, check your logins. You must be able to login on https://www.imaprotect.com.

Cette erreur provient d'une intégration personnalisée

Enregistreur: homeassistant
Source: custom_components/imaprotect/camera.py:85
intégration: IMA Protect Alarm (documentation, problèmes)
S'est produit pour la première fois: 09:21:06 (1 occurrences)
Dernier enregistrement: 09:21:06

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 261, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 417, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
    update_callback()
  File "/config/custom_components/imaprotect/camera.py", line 85, in _handle_coordinator_update
    mycam = self.coordinator.data["cameras"][self._attr_name]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'garage'


Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.imaprotect
Source: helpers/update_coordinator.py:318
intégration: IMA Protect Alarm (documentation, problèmes)
S'est produit pour la première fois: 01:51:10 (2 occurrences)
Dernier enregistrement: 02:43:28

Unexpected error fetching imaprotect data: cannot access local variable 'response' where it is not associated with a value
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fa057da8d10>, 'Connection to www.imaprotect.com timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.imaprotect.com', port=443): Max retries exceeded with url: /fr/client/management/status (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa057da8d10>, 'Connection to www.imaprotect.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyimaprotect/__init__.py", line 62, in status
    response = self._session.get(url)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.imaprotect.com', port=443): Max retries exceeded with url: /fr/client/management/status (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa057da8d10>, 'Connection to www.imaprotect.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/imaprotect/coordinator.py", line 60, in _async_update_data
    status = await self.hass.async_add_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyimaprotect/__init__.py", line 75, in status
    % (response.status_code)
       ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value

**Comment by Chrilk** [comment]
Bonjour,

Je constate le même souci.

En récupérant les sources de pyimaprotect-3.1.5, et en regardant dans __init.py, j'ai bêtement exécuté dans un interpréteur Python une par une les commandes permettant de se connecter et de vérifier l'état de l'alarme.
J'ai bien abouti à l'erreur `Can't get the token to read the status, step 'Login/TokenStatus'` car après lancement de la ligne `token_search = re.findall(RE_ALARM_TOKEN, response.text)` j'ai obtenu une chaîne vide.
J'ai donc regardé le contenu de response.text, et j'ai constaté qu'IMA Protect a encore modifié des choses dans son code, comme la fois précédente qui a entraîné les dernières modifications de pyimaprotect.
Cette fois-ci, il faut juste remplacer
`RE_ALARM_TOKEN = 'alarm-status ref="myAlarm" data-token="(.*)"'`
par
`RE_ALARM_TOKEN = 'alarm-status token="(.*)"' `

Ensuite j'arrive bien à récupérer le token, et à obtenir l'état de l'alarme.

Bref, je suppose qu'il suffirait de faire cette modification de la constante RE_ALARM_TOKEN à la ligne 30 dans le fichier __init.py du module pyimaprotect, puis modifier la version dans la section requirements du manifest.json du module imaprotect.

J'ai essayé de faire la modification, j'ai créé une pull request, j'espère que ce sera testé et validé (ou corrigé si j'ai raté quelque chose) par un mainteneur.

Merci !

**Comment by pcourbin** [comment]
Bonjour @Chrilk, @werkey, 

Merci pour vos retours et pour la correction @Chrilk !
Je viens de mettre à jour une pre-release, je vous laisse tester avant de la mettre en release (elle soit apparaître en "beta" sur HA).

Comme je l'ai mentionné précédemment, puisque je n'ai plus cette alarme, si vous souhaitez être ajouté pour faire les déploiements directement, n'hésitez pas à me le dire surtout.

**Comment by Chrilk** [comment]
Bonjour,

Merci beaucoup !
Je viens d'installer la beta, j'arrive bien à piloter de nouveau mon alarme depuis HA.

**Comment by werkey** [comment]
Bonjour, merci pour vos retour rapide ! problème complètement clos de mon coté
Je n'ai jamais géré de projet sur github mais merci de la proposition
